name: auxilia_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:

  audioplayers: ^6.4.0
  cupertino_icons: ^1.0.6
  file_picker: ^10.1.9  # Versión más estable para web
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_tts: ^3.8.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  google_generative_ai: ^0.2.2
  http: ^1.4.0
  image_picker: ^1.0.4
  permission_handler: ^11.3.1
  speech_to_text: ^7.0.0
  url_launcher: ^6.2.5
  path_provider: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagenes/Auxilia.png
    - assets/imagenes/logo.png  
    - assets/imagenes/logohorizontal.png
    - assets/imagenes/2.png
    - assets/imagenes/avatar_ba_1.png
    - assets/imagenes/avatar_bc_1.png
    - assets/imagenes/avatar_bc_2.png
    - assets/imagenes/avatar_ba_2.png


  fonts:
    - family: CarterOne
      fonts:
        - asset: assets/fonts/Carter_One/CarterOne-Regular.ttf
