version: '3.9'
services:
  api:
    build: ./backend
    env_file: ./.env
    ports: ['8080:8080']
    depends_on: [mongo]
  worker:
    build: ./worker
    depends_on: [api]
  mongo:
    image: mongo:7
    ports: ['27017:27017']
    volumes: ['mongo_data:/data/db']
  ollama:
    image: ollama/ollama
    ports: ['11434:11434']
volumes:
  mongo_data:
